# Note  : *** the batch_size should be equal to the gpus number at the test phase!!! ***
data_cfg:
  dataset_name: SLR
  dataset_root: /fuxi_cv/SSL/original_1stage_data/data_sorted_pose_resize_vis_norm_npy/
  dataset_partition: /root/LBB/OpenSLR/datasets/SLR80.json
  num_workers: 1
  remove_no_gallery: false
  test_dataset_name: i3d_mlp

evaluator_cfg:
  enable_distributed: true
  enable_float16: false
  restore_ckpt_strict: true
  restore_hint: 80000
  save_name: SLR
  sampler:
    batch_size: 2
    sample_type: all_ordered
    type: InferenceSampler
  transform:
    - type: BaseRgbNormTransform

loss_cfg:
#  - loss_term_weight: 1.0
#    margin: 0.2
#    type: TripletLoss
#    log_prefix: triplet
  - loss_term_weight: 1.0
    scale: 1
    type: CrossEntropyLoss
    log_accuracy: true
    label_smooth: false
    log_prefix: softmax

model_cfg:
  model: i3d_mlp
  channels: [32, 64, 128]
  class_num: 60
  SeparateBNNecks:
    class_num: 60
    in_channels: 1024
    parts_num: 1

optimizer_cfg:
  lr: 0.1
  momentum: 0.9
  solver: SGD
  weight_decay: 0.0005

scheduler_cfg:
  gamma: 0.1
  milestones: # Learning Rate Reduction at each milestones
    - 500
    - 1000
    - 1500
    - 2000
  scheduler: MultiStepLR

trainer_cfg:
  enable_distributed: true
  enable_float16: false
  log_iter: 10
  restore_ckpt_strict: false
  optimizer_reset: true
  scheduler_reset: true
  restore_hint: 10
  save_iter: 10
  save_name: i3d_mlp
  sync_BN: true
  total_iter: 2500
  sampler:
    batch_shuffle: true
    batch_size:
      - 6
      - 2
    frames_num_fixed: 16
    frames_skip_num: 0
    sample_type: fixed_ordered
    type: TripletSampler
  transform:
    - type: BaseRgbNormTransform
