# Note  : *** the batch_size should be equal to the gpus number at the test phase!!! ***
data_cfg:
  dataset_name: SLR
  dataset_root: /root/SSL/data/data_sorted_pose_pkl
  dataset_partition: ./datasets/SLR.json
  num_workers: 1
  remove_no_gallery: false
  test_dataset_name: SLR_Pose

evaluator_cfg:
  enable_distributed: true
  enable_float16: false 
  restore_ckpt_strict: true
  restore_hint: 80000
  save_name: SLR
  sampler:
    batch_size: 4
    sample_type: all_ordered
    type: InferenceSampler
  transform:
    - type: BasePosejointTransform

loss_cfg:
  - loss_term_weight: 1.0
    margin: 0.2
    type: TripletLoss
    log_prefix: triplet
  - loss_term_weight: 1.0
    scale: 1
    type: CrossEntropyLoss
    log_accuracy: true
    label_smooth: false
    log_prefix: softmax

model_cfg:
  model: SLR_Pose
  class_num: 60
  SeparateBNNecks:
    class_num: 60
    in_channels: 256
    parts_num: 81


optimizer_cfg:
  lr: 0.1
  momentum: 0.9
  solver: SGD
  weight_decay: 0.0005

scheduler_cfg:
  gamma: 0.1
  milestones: # Learning Rate Reduction at each milestones
    - 500
    - 1000
    - 1500
    - 2000
  scheduler: MultiStepLR

trainer_cfg:
  enable_distributed: true
  enable_float16: false
  log_iter: 10
  restore_ckpt_strict: false
  optimizer_reset: true
  scheduler_reset: true
  restore_hint: 10
  save_iter: 100
  save_name: SLR_Pose
  sync_BN: true
  total_iter: 2500
  sampler:
    batch_shuffle: true
    batch_size:
      - 12
      - 4
    frames_num_fixed: 16
    frames_skip_num: 0
    sample_type: fixed_ordered
    type: TripletSampler
  transform:
    - type: BasePosejointTransform
