# Note  : *** the batch_size should be equal to the gpus number at the test phase!!! ***
data_cfg:
  dataset_name: SLR
  #dataset_root: /data/SSL/SSL/data/data_sorted_pose_pkl
  #dataset_root: /data/SSL/SSL/data_sorted_3Dposepkl ## original trainset
  dataset_root: /data/SSL/SSL/all_3D_train_val ## all = train + val
  dataset_partition: /root/LBB/OpenSLR/datasets/SLR80.json
  num_workers: 1
  remove_no_gallery: false
  test_dataset_name: SLR_DecoupleFv4

evaluator_cfg:
  enable_distributed: true
  enable_float16: false 
  restore_ckpt_strict: true
  restore_hint: 80000
  save_name: SLR
  sampler:
    batch_size: 4
    sample_type: all_ordered
    type: InferenceSampler
  transform:
    - type: BasePosejointTransform3D

loss_cfg:
  - loss_term_weight: 1.0
    margin: 0.2
    type: TripletLoss
    log_prefix: triplet
  - loss_term_weight: 1.0
    scale: 1
    type: CrossEntropyLoss
    log_accuracy: true
    label_smooth: false
    log_prefix: softmax

model_cfg:
  model: SLR_pose3D
  channels: [64, 128, 256]
  class_num: 80
  SeparateBNNecks:
    class_num: 80
    in_channels: 256
    parts_num: 39 #78


optimizer_cfg:
  lr: 0.1
  momentum: 0.9
  solver: SGD
  weight_decay: 0.0005

scheduler_cfg:
  gamma: 0.1
  milestones: # Learning Rate Reduction at each milestones
    - 150
    - 200
    - 250
    - 350
  scheduler: MultiStepLR

trainer_cfg:
  enable_distributed: true
  enable_float16: false
  log_iter: 10
  restore_ckpt_strict: false
  optimizer_reset: true
  scheduler_reset: true
  restore_hint: 0
  save_iter: 10
  save_name: SLR_pose3D
  sync_BN: true
  total_iter: 500
  sampler:
    batch_shuffle: true
    batch_size:
      - 12
      - 4
    frames_num_fixed: 16
    #frames_num_max: 25
    #frames_num_min: 10
    frames_skip_num: 0
    sample_type: fixed_ordered #unfixed_ordered 
    type: TripletSampler
  transform:
    - type: BasePosejointTransform3D
